/**
 * Biblioteca de 112 Quick Commands (7 por agente x 16 agentes).
 * Suporta placeholders: {{cliente}}, {{segmento}}, {{step}}, {{pilar}}
 */

import { applyPlaceholders } from './templates';

export interface QuickCommand {
  id: string;
  agentId: string;
  label: string;
  description: string;
  prompt: string;
  category: string;
}

export const QUICK_COMMANDS: QuickCommand[] = [
  // ===== AGENTE 01 - MESTRE ESTRATEGISTA =====
  { id: '01-diag', agentId: '01', label: 'Diagnostico STEP completo', category: 'Estrategia', description: 'Analise 360 do cliente', prompt: 'Faca diagnostico completo STEP+TOC+AEMR para {{cliente}} ({{segmento}}). Identifique restricao primaria, aplique FCA, priorize com ICE, recomende cadeia inter-agentes com prazos. Inclua benchmarks do segmento e metas 30/60/90d.' },
  { id: '01-sprint', agentId: '01', label: 'Sprint Planning semanal', category: 'Sprint', description: 'Planejamento da semana', prompt: 'Monte sprint planning semanal para {{cliente}} considerando fase {{step}} e pilar {{pilar}}. 8-12 tarefas P1/P2/P3 por agente, criterios de sucesso, prazo. Metas SMART da semana.' },
  { id: '01-relatorio', agentId: '01', label: 'Relatorio mensal C-level', category: 'Relatorio', description: 'Consolidado mensal', prompt: 'Gere relatorio mensal C-level para {{cliente}}: resumo executivo, KPIs por pilar AEMR, analise throughput TOC, top 3 vitorias, top 3 gargalos, recomendacoes priorizadas ICE. Formate para envio ao cliente.' },
  { id: '01-nbo', agentId: '01', label: 'Next Best Offer (NBO)', category: 'Expansao', description: 'Proximo produto V4', prompt: 'Apos diagnostico de {{cliente}}, rode NBO score: rankie produtos V4 por (Impact x Prerequisites x Conversion) / Investment. Top 3 recomendados com justificativa TOC + Forecast 12M.' },
  { id: '01-forecast', agentId: '01', label: 'Forecast 12 meses', category: 'Projecao', description: '12M com cenarios', prompt: 'Construa Forecast 12M para {{cliente}}. Inputs: trafego, leads, SQLs, vendas, ticket medio, conversion rates por etapa. Simule 3 cenarios (conservador/realista/otimista) com impacto financeiro.' },
  { id: '01-toc-5-passos', agentId: '01', label: 'TOC 5 Passos Focalizadores', category: 'TOC', description: 'Identificar e elevar restricao', prompt: 'Aplique os 5 passos focalizadores TOC para {{cliente}}: 1) IDENTIFICAR restricao (onde fila acumula?), 2) EXPLORAR ao max, 3) SUBORDINAR, 4) ELEVAR, 5) REPETIR. Com planos concretos e orcamento.' },
  { id: '01-current-reality-tree', agentId: '01', label: 'Current Reality Tree', category: 'Thinking Process', description: 'Mapa causal raiz', prompt: 'Construa Current Reality Tree (TOC Thinking Process) para {{cliente}}: liste UDEs (Undesirable Effects), mapeie cadeias causais de volta ate root causes. Apresente visualmente em markdown.' },

  // ===== AGENTE 02 - GESTOR DE PROJETOS =====
  { id: '02-backlog', agentId: '02', label: 'Refinar backlog RICE', category: 'Backlog', description: 'Priorizacao RICE', prompt: 'Refine backlog de {{cliente}} com RICE (Reach, Impact, Confidence, Effort). Criterios de aceite claros, dependencias, story points. Identifique bloqueios + plano.' },
  { id: '02-raci', agentId: '02', label: 'RACI Matrix projeto', category: 'Governance', description: 'Responsabilidades', prompt: 'Monte RACI matrix completa para {{cliente}}: 10-15 atividades x 6 papeis (Cliente, Coord, Trafego, Copy, Design, Dev). Responsible/Accountable/Consulted/Informed.' },
  { id: '02-okrs-trimestre', agentId: '02', label: 'OKRs trimestrais', category: 'OKR', description: '3 objetivos x 5 KRs', prompt: 'Defina OKRs trimestrais para {{cliente}}: 3 objetivos ambiciosos alinhados ao {{pilar}}, cada um com 3-5 Key Results SMART (baseline, target, metodo medicao). Check-in quinzenal.' },
  { id: '02-retro', agentId: '02', label: 'Retrospectiva Sprint', category: 'Retro', description: 'Start/Stop/Continue', prompt: 'Facilite retrospectiva da ultima sprint de {{cliente}}: O que funcionou, O que nao funcionou, O que aprendemos, Acoes concretas. Foque em processo + colaboracao.' },
  { id: '02-critical-chain', agentId: '02', label: 'Critical Chain', category: 'Scheduling', description: 'Caminho critico com buffer', prompt: 'Aplique Critical Chain (TOC) para projeto de {{cliente}}: identifique caminho critico, elimine multitasking, posicione buffers de projeto + alimentacao. Cronograma com folgas visiveis.' },
  { id: '02-capacity', agentId: '02', label: 'Capacity Planning', category: 'Capacity', description: 'Planejamento de recursos', prompt: 'Planejamento de capacidade de {{cliente}}: estime demanda (horas/agente/sprint), compare com capacidade atual, identifique gargalos de recursos. Cenarios com/sem contratacao.' },
  { id: '02-standups-template', agentId: '02', label: 'Template Daily Standups', category: 'Cerimonias', description: 'Formato de daily', prompt: 'Crie template de daily standup para {{cliente}}: 3 perguntas (fiz/faco/bloqueios), regras de tempo, formato assincrono/sincrono. Template para Slack/Notion.' },

  // ===== AGENTE 03 - TRAFEGO GOOGLE =====
  { id: '03-campanha', agentId: '03', label: 'Estrutura campanha Search', category: 'Campanha', description: 'Grupos + copies + extensoes', prompt: 'Cria estrutura COMPLETA campanha Google Search para {{cliente}} ({{segmento}}). 4 grupos (marca, produto, problema, competidor), 15 keywords/grupo com match types, 15 RSA headlines + 4 descriptions/grupo, 6 sitelinks, 4 callouts, 3 snippets. Orcamento + tCPA.' },
  { id: '03-pmax', agentId: '03', label: 'Performance Max setup', category: 'Campanha', description: 'PMax com assets/audiencias', prompt: 'Monte campanha PMax para {{cliente}}: 20 headlines (30c), 5 long headlines (90c), 5 descriptions (90c), 20 imagens specs, 5 videos, URLs, audience signals, feeds produto, conversoes prioritarias, bidding.' },
  { id: '03-quality-score', agentId: '03', label: 'Audit Quality Score', category: 'Audit', description: 'QS diagnostico + plano', prompt: 'Audit QS conta {{cliente}}. Check: relevancia keyword-ad por grupo, CTR esperado, experiencia LP. Top 10 keywords com QS baixo + plano melhoria por keyword.' },
  { id: '03-keywords-negativas', agentId: '03', label: 'Lista keywords negativas', category: 'Keywords', description: '50+ negativas por segmento', prompt: 'Lista completa keywords negativas para {{cliente}} ({{segmento}}): (1) gratis/free/download, (2) concorrentes diretos, (3) search terms fora do funil, (4) irrelevantes segmento, (5) baixa conversao. Min 50/categoria.' },
  { id: '03-search-shopping', agentId: '03', label: 'Search + Shopping combo', category: 'Campanha', description: 'Search+Shopping coordenados', prompt: 'Desenhe estrategia Search + Shopping combinada para {{cliente}}. Segmentacao, feed de produtos, campanhas Brand/Non-Brand/Shopping Smart. Budget split otimizado.' },
  { id: '03-remarketing-list', agentId: '03', label: 'Listas de remarketing RLSA', category: 'Audiencia', description: 'RLSA por funil', prompt: 'Crie listas RLSA para {{cliente}}: visitantes 30d, carrinho abandonado 7d, clientes 90d. Estrategia de lance (+30% a +200%) e copy personalizada.' },
  { id: '03-youtube-ads', agentId: '03', label: 'Campanha YouTube Ads', category: 'Video', description: 'In-stream + Discovery', prompt: 'Estruture campanha YouTube Ads para {{cliente}}: formatos (in-stream skippable, bumper 6s, discovery), roteiros 15s/30s/60s, targeting, bidding CPV, metas view rate 30%+.' },

  // ===== AGENTE 04 - TRAFEGO META =====
  { id: '04-conversao', agentId: '04', label: 'Campanha conversao Meta', category: 'Campanha', description: 'CBO + 4 conjuntos', prompt: 'Estruture campanha conversao Meta Ads para {{cliente}}. CBO, 4 conjuntos (LAL 1%, LAL 3%, Interesses, Broad 25-55), 5 criativos/conjunto (video hook, carrossel, imagem, UGC, before/after). Pixel+CAPI, kill rules, escala +20%/3d.' },
  { id: '04-escala', agentId: '04', label: 'Plano escala orcamento', category: 'Escala', description: 'Vertical + horizontal', prompt: 'Plano escala para {{cliente}} Meta: triggers (CPA<80% por 3d), kill rules (CPA>2x por 3d), escala vertical +20%/3d, escala horizontal (duplicar vencedor em novo publico), rotacao criativos, metas fase.' },
  { id: '04-lookalike', agentId: '04', label: 'Estrategia Lookalikes', category: 'Audiencia', description: '5 fontes ranqueadas', prompt: 'Estrategia LAL para {{cliente}}: top 5 fontes ranked por valor (top 10% compradores, compradores, LTV alto, SQLs, trafego engajado). LAL 1%/1-3%/3-5% cada. Exclusoes, tamanho min, refresh semanal.' },
  { id: '04-retargeting', agentId: '04', label: 'Retargeting por estagio', category: 'Retargeting', description: 'TOFU/MOFU/BOFU', prompt: 'Retargeting Meta por estagio funil {{cliente}}: (1) TOFU visitou blog 30d, (2) MOFU visitou produto 14d, (3) BOFU carrinho 7d, (4) Abandono checkout 3d, (5) Clientes 60d+ upsell. Copy+criativos/estagio.' },
  { id: '04-creative-testing', agentId: '04', label: 'Framework teste criativos', category: 'Testes', description: '5x5 test matrix', prompt: 'Design framework teste criativos Meta para {{cliente}}: matriz 5x5 (5 hooks x 5 formatos), metricas por etapa (hook rate, CTR, CPA), budget testing, iteracao semanal.' },
  { id: '04-instagram-reels', agentId: '04', label: 'Campanha Reels Ads', category: 'Formatos', description: 'Criativos nativos Reels', prompt: 'Estruture campanha Reels Ads para {{cliente}}: 5 conceitos (tutorial, antes/depois, UGC, POV, storytime), specs 9:16 15s, hooks nos 3s, som trending, copy vertical. Budget e targeting.' },
  { id: '04-capi-setup', agentId: '04', label: 'Setup Conversions API', category: 'Tracking', description: 'CAPI server-side', prompt: 'Documento setup CAPI para {{cliente}}: escolha implementacao (Shopify app, GTM server, Zapier), eventos mapeados, deduplicacao com Pixel, quality score 8+. Teste com Event Manager.' },

  // ===== AGENTE 05 - DESIGNER ADS =====
  { id: '05-brief', agentId: '05', label: 'Brief criativo completo', category: 'Brief', description: 'Brief para pack de ads', prompt: 'Escreva brief criativo completo para {{cliente}}: objetivo, publico-alvo + dores, proposta valor, 5 variacoes mensagem (beneficio/prova/urgencia/problema-solucao/before-after), guidelines marca, specs Meta+Google+YT, referencias.' },
  { id: '05-pack-10', agentId: '05', label: 'Pack 10 conceitos', category: 'Conceitos', description: '10 conceitos para A/B', prompt: 'Gere pack 10 conceitos criativos para {{cliente}} ({{segmento}}). Cada: headline visual, elemento principal, CTA, angulo psicologico (escassez/prova/autoridade), formato ideal (estatico/video/carrossel).' },
  { id: '05-banner-gerar', agentId: '05', label: 'GERAR banner via Nano Banana', category: 'Geracao', description: 'Cria imagem inline', prompt: 'Gere imagem de banner para {{cliente}} ({{segmento}}). Formato 1:1, copy headline destacado, visual clean/moderno. Cores primarias e secundarias da marca. Estilo foto real ou ilustracao (detectar melhor opcao).' },
  { id: '05-variacoes-ab', agentId: '05', label: 'Variacoes A/B visual', category: 'A/B', description: '5 variacoes mesma mensagem', prompt: 'Crie 5 variacoes A/B visual mesma mensagem para {{cliente}}: (A) texto-first, (B) imagem-first, (C) UGC style, (D) minimalista, (E) bold contrast. Specs e hipoteses.' },
  { id: '05-carrossel', agentId: '05', label: 'Carrossel 5 slides', category: 'Carrossel', description: 'Roteiro + designs', prompt: 'Conceito carrossel 5 slides para {{cliente}}: hook capa, 3 slides desenvolvimento, 1 slide CTA. Texto por slide, sugestao visual, transicoes.' },
  { id: '05-refresh-urgente', agentId: '05', label: 'Refresh criativos (fadiga)', category: 'Fadiga', description: 'Novos conceitos com frequencia 3.5+', prompt: 'Refresh urgente criativos de {{cliente}} (Freq>3.5). 3 novos angulos completamente diferentes: (1) problema diferente, (2) prova social nova, (3) urgencia/escassez. Specs + copy.' },
  { id: '05-specs-canais', agentId: '05', label: 'Specs oficiais por canal', category: 'Specs', description: 'Cheat-sheet por canal', prompt: 'Gere cheat-sheet specs criativos por canal para {{cliente}}: Meta (Feed 1:1/4:5, Reels 9:16, Stories 9:16), Google (Display tamanhos, YouTube 16:9 + 9:16 Shorts), LinkedIn, TikTok.' },

  // ===== AGENTE 06 - DESIGNER SOCIAL =====
  { id: '06-brand', agentId: '06', label: 'Brand Guidelines basico', category: 'Brand', description: 'Manual de marca MVP', prompt: 'Crie brand guidelines basico para {{cliente}}: paleta (primaria/secundaria/neutras com hex), tipografia (headlines/body/specs), logo usage, tom de voz (3 pilares do/dont), iconografia, fotos diretrizes.' },
  { id: '06-templates', agentId: '06', label: 'Templates social (10 modelos)', category: 'Templates', description: 'Biblioteca de posts', prompt: '10 templates posts para {{cliente}}: motivacional, dica rapida, carrossel 5 slides, before-after, case, pergunta engajamento, meme, bastidores, lancamento, oferta. Specs IG feed/stories/reels.' },
  { id: '06-carousel-design', agentId: '06', label: 'Design carrossel educativo', category: 'Carrossel', description: 'Carrossel 10 slides', prompt: 'Design carrossel educativo 10 slides para {{cliente}}: capa gancho, 8 slides conteudo (icone+titulo+tex), slide final CTA. Layout consistente, hierarquia clara.' },
  { id: '06-stories-pack', agentId: '06', label: 'Pack 15 stories', category: 'Stories', description: 'Stories semana inteira', prompt: 'Pack 15 stories para {{cliente}} (semana inteira): mix de enquete, slider, quiz, conteudo, bastidores, produto, CTA. Layouts e copy.' },
  { id: '06-visual-identity', agentId: '06', label: 'Visual identity refresh', category: 'Identidade', description: 'Refresh mantendo essencia', prompt: 'Proposta refresh visual identity {{cliente}}: analise posicionamento atual, 3 direcoes (evolucao/moderna/disruptiva), mockups por direcao, recomendacao.' },
  { id: '06-highlights-covers', agentId: '06', label: 'Covers Highlights Instagram', category: 'Perfil', description: 'Covers para 8 destaques', prompt: 'Design 8 covers Highlights Instagram {{cliente}}: minimalistas, cores brand, icones unificados, categorias (Sobre/Produtos/Cases/Depoimentos/Dicas/Bastidores/FAQ/Contato).' },
  { id: '06-link-bio-page', agentId: '06', label: 'Link in Bio page design', category: 'Link-in-bio', description: 'Landing do link in bio', prompt: 'Design pagina link in bio para {{cliente}}: layout mobile-first, 6-8 botoes priorizados, copy curto, visual brand. Specs Linktree/Beacons/LinkTree.' },

  // ===== AGENTE 07 - SOCIAL MEDIA =====
  { id: '07-calendario', agentId: '07', label: 'Calendario editorial mes', category: 'Calendario', description: '30 posts 70/20/10', prompt: 'Calendario editorial mensal {{cliente}} (IG + LinkedIn): 30 posts mix 70/20/10 (educativo/prova/venda). Para cada: data, canal, pilar, titulo, legenda 120-150 pal, hashtags 15-30, CTA, tipo midia.' },
  { id: '07-legendas-10', agentId: '07', label: 'Pack 10 legendas', category: 'Legendas', description: '10 legendas virais', prompt: '10 legendas Instagram {{cliente}} ({{segmento}}): mix educativas (hooks fortes), historias/cases, polemicas/contrarian, pergunta, lancamento, convite DM. Hashtags estrategicas + CTA.' },
  { id: '07-hashtags', agentId: '07', label: 'Estrategia hashtags', category: 'Hashtags', description: '30 hashtags mix', prompt: 'Estrategia hashtags {{cliente}} ({{segmento}}): 30 hashtags divididas: 5 top (>1M posts), 10 medium (100k-1M), 10 nicho (10k-100k), 5 local/geo. Analise competitors. 3 sets rotativos.' },
  { id: '07-concorrentes', agentId: '07', label: 'Analise 5 concorrentes', category: 'Benchmark', description: 'Benchmark social', prompt: 'Analise 5 principais concorrentes {{cliente}} no IG: seguidores, engagement rate, frequencia, top 3 posts engajados (porque), tom de voz, mix conteudo, uso stories/reels, oportunidades diferenciacao.' },
  { id: '07-tiktok-strategy', agentId: '07', label: 'Estrategia TikTok', category: 'TikTok', description: 'Plano TikTok especifico', prompt: 'Plano TikTok {{cliente}}: niche definition, 5 pilares conteudo, audios trending analysis, frequencia postagem, 10 ideias videos por pilar, metas view/engagement/follow.' },
  { id: '07-community-management', agentId: '07', label: 'Playbook Community Management', category: 'Community', description: 'SLA + tom de resposta', prompt: 'Playbook community management {{cliente}}: SLA resposta (<15min horario comercial), tom de voz nas respostas, template comum, escalation para duvidas tecnicas/reclamacoes, policy + FAQ publico.' },
  { id: '07-live-streaming-plan', agentId: '07', label: 'Plano Live Streaming', category: 'Live', description: 'Lives mensais para engajar', prompt: 'Plano Live Streaming {{cliente}}: 2-4 lives/mes por pilar, formatos (Q&A, entrevista expert, tutorial, bastidores), roteiros, promocao 7d antes, repurpose pos-live em posts/clips.' },

  // ===== AGENTE 08 - COPY PERFORMANCE =====
  { id: '08-lp-completa', agentId: '08', label: 'Copy LP completa', category: 'LP', description: 'LP com 9 secoes', prompt: 'Copy COMPLETA LP {{cliente}} ({{segmento}}): (1)Hero H1+sub+CTA, (2)Problema 3-4 bullets dor, (3)Solucao proposta valor, (4)Beneficios 6 com icones, (5)Como funciona 3 passos, (6)Prova social depoimentos+numeros+logos, (7)Oferta irresistivel, (8)FAQ 8 perguntas, (9)CTA final com urgencia. Use PAS ou AIDA.' },
  { id: '08-headlines-15', agentId: '08', label: '15 headlines A/B', category: 'Headlines', description: 'Headlines com frameworks', prompt: '15 headlines A/B test {{cliente}}: mix (1-3) numero+beneficio, (4-6) pergunta, (7-9) problema-solucao, (10-12) prova social, (13-15) urgencia/escassez. Variacoes mesmo angulo.' },
  { id: '08-email-pas', agentId: '08', label: 'Email vendas (PAS)', category: 'Email', description: 'Email completo framework PAS', prompt: 'Email vendas {{cliente}} framework PAS. 4 variacoes assunto, pre-header, corpo: abertura relatable, problema, agitacao, solucao, prova, oferta, CTA, PS urgencia. 400-600 palavras.' },
  { id: '08-ctas-30', agentId: '08', label: '30 CTAs por etapa funil', category: 'CTA', description: 'CTAs TOFU/MOFU/BOFU', prompt: '30 CTAs {{cliente}} por etapa funil: 10 TOFU (suave), 10 MOFU (beneficio), 10 BOFU (acao direta). Cada: texto + contexto uso + expectativa CTR.' },
  { id: '08-vsl-script', agentId: '08', label: 'VSL Script 20min', category: 'VSL', description: 'Video Sales Letter roteiro', prompt: 'Roteiro VSL 20min para {{cliente}}: estrutura (0-2min hook+promessa, 2-8min problema+agitacao, 8-14min solucao+como funciona, 14-17min prova social, 17-20min oferta+CTA). Marcacoes visuais.' },
  { id: '08-upsell-copy', agentId: '08', label: 'Copy upsell pos-compra', category: 'Upsell', description: 'One-time offer', prompt: 'Copy upsell pos-compra {{cliente}}: OTO pagina, 3 variacoes (complementar/upgrade/VIP), bullet points valor, urgencia genuina, CTA duplo (aceitar/declinar).' },
  { id: '08-objections-script', agentId: '08', label: 'Script objeções (10)', category: 'Objecoes', description: 'Responder 10 objecoes comuns', prompt: 'Script respondendo 10 objecoes comuns {{cliente}}: preco, tempo, confianca, necessidade, comparar com concorrente. Cada: reformulacao + prova + convite.' },

  // ===== AGENTE 09 - COPY CONTEUDO =====
  { id: '09-artigo-2000', agentId: '09', label: 'Artigo blog completo (2000+)', category: 'Blog', description: 'Artigo SEO 2000 palavras', prompt: 'Artigo COMPLETO blog {{cliente}} sobre [TEMA]. 2000+ palavras. Estrutura: title SEO + meta desc 155c + intro hook + sumario + 5-7 H2 com H3 + listas/tabelas/exemplos + conclusao com CTA + 5 FAQs schema-ready + 3 imagens com alt + 5 keywords secundarias naturais.' },
  { id: '09-email-sequencia', agentId: '09', label: 'Sequencia 7 emails nutricao', category: 'Email', description: 'Fluxo de 14 dias', prompt: 'Sequencia nutricao por email {{cliente}} (7 emails em 14 dias). E1 boas-vindas+isca, E2-3 historia/credibilidade, E4 problema+educacao, E5 case sucesso, E6 oferta+bonus, E7 urgencia final. Cada: assunto 3 variacoes + pre-header + corpo 300-500 + CTA + PS.' },
  { id: '09-ebook-completo', agentId: '09', label: 'E-book estrutura + cap modelo', category: 'Ebook', description: 'Livro digital', prompt: 'Estrutura COMPLETA e-book {{cliente}} sobre [TEMA] 30-40 pag: titulo+subtitulo vendedor, sumario 7-8 caps, introducao completa, 1 capitulo modelo COMPLETO (2000 palavras) template, conclusao+CTA, sugestao diagramacao.' },
  { id: '09-newsletter', agentId: '09', label: 'Newsletter semanal', category: 'Newsletter', description: 'Template autoridade', prompt: 'Newsletter semanal {{cliente}} ({{segmento}}): assunto curiosidade, abertura pessoal, 1 insight principal da semana, 3 tips acionaveis, 1 ferramenta recomendada, 1 pergunta engajamento, CTA suave produto. 600-800 pal tom conversacional.' },
  { id: '09-case-study', agentId: '09', label: 'Case Study cliente', category: 'Case', description: 'STAR framework', prompt: 'Case study COMPLETO {{cliente}} STAR: (1)Situacao inicial com numeros, (2)Task/desafio, (3)Acoes detalhe metodologico, (4)Resultados KPIs com % melhoria, (5)Depoimento cliente, (6)Licoes. 1200 pal + grafico/tabela.' },
  { id: '09-white-paper', agentId: '09', label: 'White paper tecnico', category: 'White paper', description: 'B2B autoridade', prompt: 'White paper tecnico B2B {{cliente}} ({{segmento}}): 15-20 pag, executive summary, problema de mercado, abordagem proprietaria, dados/benchmarks, 3 cases, conclusao com CTA. Tom academico-executivo.' },
  { id: '09-linkedin-article', agentId: '09', label: 'Artigo LinkedIn 1500', category: 'LinkedIn', description: 'Thought leadership', prompt: 'Artigo LinkedIn thought leadership {{cliente}} 1500 pal: hook na 1a linha, historia/data pessoal, framework/mental model, 3-5 exemplos concretos, aprendizado principal, pergunta engajamento, CTA comentario.' },

  // ===== AGENTE 10 - AUTOMACOES =====
  { id: '10-fluxo-nutricao', agentId: '10', label: 'Fluxo nutricao RD/HubSpot', category: 'Fluxo', description: 'Com triggers + condicionais', prompt: 'Fluxo nutricao automacao {{cliente}} RD Station/HubSpot: trigger (lead converte X), 7 emails delays (1d/3d/5d/8d/11d/14d/20d), condicionais (abriu/clicou/respondeu/adicionou tag), desvios (quente SDR, frio nutricao longa). Diagrama md + config passo-a-passo.' },
  { id: '10-lead-scoring', agentId: '10', label: 'Modelo Lead Scoring', category: 'Lead Scoring', description: 'Perfil + engajamento', prompt: 'Modelo Lead Scoring {{cliente}}: duas dimensoes (PERFIL cargo/empresa/segmento/orcamento + ENGAJAMENTO paginas/downloads/emails/webinar/respondeu). Pontos por acao, thresholds (MQL>50, SQL>80), decay -10/semana. Export tabela RD/HubSpot.' },
  { id: '10-webhook', agentId: '10', label: 'Setup webhook integracao', category: 'Integracao', description: 'Webhook entre sistemas', prompt: 'Setup webhook {{cliente}} conectando [sistema A] com [B]: endpoint URL, payload JSON schema, auth, triggers, testes curl, error handling, retry logic, logs. Alternativa no-code Zapier/Make.' },
  { id: '10-zapier-100', agentId: '10', label: '10 automacoes Zapier uteis', category: 'Zapier', description: 'Zaps para escala', prompt: '10 automacoes Zapier {{cliente}}: form>CRM, CRM>Slack+email, calendar>proposta, Stripe>Notion, Typeform>Sheets>Slack, etc. Zaps com triggers/acoes/filtros.' },
  { id: '10-chatbot-whatsapp', agentId: '10', label: 'Chatbot WhatsApp fluxo', category: 'Chatbot', description: 'Bot atendimento inicial', prompt: 'Fluxo chatbot WhatsApp {{cliente}}: menu principal 5 opcoes, subfluxos (FAQ, agendamento, compra, suporte, humano), respostas template, handoff para humano, horario comercial, metricas resolucao.' },
  { id: '10-abandoned-cart', agentId: '10', label: 'Fluxo carrinho abandonado', category: 'E-com', description: 'Recovery e-commerce', prompt: 'Fluxo carrinho abandonado {{cliente}} e-commerce: gatilho (2h apos abandono), email 1 (amigavel lembrete), email 2 (+24h social proof), email 3 (+48h desconto 10%), WhatsApp se tem numero, SMS. Copy cada toque.' },
  { id: '10-salesforce-crm-sync', agentId: '10', label: 'Sync RD<>Salesforce', category: 'CRM Sync', description: 'Integracao bidirecional', prompt: 'Integracao bidirecional RD Station <> Salesforce {{cliente}}: fields mapping, rules de deduplicacao, trigger MQL>SQL, bounce back se inativo, logs audit trail. Sequencia implementacao tecnica.' },

  // ===== AGENTE 11 - CRM =====
  { id: '11-pipeline-review', agentId: '11', label: 'Pipeline review completo', category: 'Pipeline', description: 'Com forecast', prompt: 'Pipeline review {{cliente}}: volume/etapa (SDR, SQL, Proposta, Negociacao, Fechado), conversion rate entre etapas (gargalo?), tempo medio/etapa, ticket medio, top 5 deals em risco, forecast conservador/realista/otimista mes, acoes corretivas ICE.' },
  { id: '11-scripts-vendas', agentId: '11', label: 'Scripts vendas por etapa', category: 'Scripts', description: 'Cold, discovery, demo, close', prompt: 'Scripts vendas {{cliente}}: (1)Cold call 30s (hook+valor+qualifier), (2)Discovery 30min (SPIN, dores, orcamento, autoridade), (3)Demo (agenda+features mapeadas dores+objecoes preventivas), (4)Close (alternativa/urgencia/assumptive). Scripts naturais.' },
  { id: '11-cadencia', agentId: '11', label: 'Cadencia followup 21d', category: 'Cadencia', description: 'Multicanal', prompt: 'Cadencia followup 21 dias {{cliente}} B2B multicanal (email+LinkedIn+WhatsApp+ligacao). Dias 1/3/5/8/11/14/17/21. Cada toque: canal, objetivo, mensagem pronta, CTA. Break-up email final.' },
  { id: '11-bant-meddic', agentId: '11', label: 'BANT + MEDDIC framework', category: 'Qualificacao', description: 'Qualificar leads', prompt: 'Framework BANT+MEDDIC {{cliente}} ({{segmento}}). BANT (Budget/Authority/Need/Timing): perguntas discovery, criterios qualifica/desqualifica, red flags, sinais verdes. MEDDIC complementar. Lead score ajustado.' },
  { id: '11-proposal-template', agentId: '11', label: 'Template proposta vencedora', category: 'Proposta', description: 'Proposta com 8 secoes', prompt: 'Template proposta {{cliente}}: (1)Resumo executivo, (2)Entendimento dor, (3)Solucao proposta, (4)Entregas detalhadas, (5)Timeline, (6)Investimento 3 opcoes, (7)Cases similares, (8)Proximos passos. Formato visual, objecoes preventivas.' },
  { id: '11-account-based-marketing', agentId: '11', label: 'Plano ABM (Account-Based)', category: 'ABM', description: 'Top 20 contas', prompt: 'Plano ABM {{cliente}}: top 20 contas-alvo com fit score, research individual (decisores, gatilhos, budget), messaging 1:1, canais por persona, orquestracao time vendas+marketing, metricas engagement+win rate.' },
  { id: '11-win-loss-analysis', agentId: '11', label: 'Win/Loss Analysis', category: 'Analise', description: 'Por que ganhou/perdeu', prompt: 'Win/Loss analysis {{cliente}} ultimos 30 deals: 15 won + 15 lost. Padroes (motivos principais), segmentacao por perfil, comparacao concorrentes, acoes corretivas pipeline + messaging + produto.' },

  // ===== AGENTE 12 - WEB DEV =====
  { id: '12-ga4-setup', agentId: '12', label: 'Setup GA4 + GTM completo', category: 'Tracking', description: 'Guia passo-a-passo', prompt: 'Guia COMPLETO setup GA4+GTM {{cliente}}: (1)criar property, (2)instalar GTM, (3)tag GA4 base, (4)enhanced measurement, (5)8 conversoes prioritarias com triggers, (6)parametros customizados, (7)audiencias Google Ads, (8)dashboard basico, (9)testes Tag Assistant.' },
  { id: '12-core-web-vitals', agentId: '12', label: 'Audit Core Web Vitals', category: 'Performance', description: 'LCP/FID/CLS', prompt: 'Audit CWV {{cliente}}. Metricas: LCP, FID/INP, CLS. Para cada: valor atual, meta, gap, top 3 causas, acoes corretivas priorizadas (lazy load, image optim, fonts, JS bundle, cache, CDN), impacto esperado SEO+conversao.' },
  { id: '12-lp-tech-spec', agentId: '12', label: 'Spec tecnica LP', category: 'LP', description: 'Para dev construir', prompt: 'Spec tecnica LP {{cliente}}: HTML semantico, hierarquia headings, schema markup (Org, Product, FAQ, Review), performance budget (<3s LCP, <200KB JS), eventos tracking (scroll, click, submit, video), WCAG AA, meta open graph, favicons, sitemap/robots.' },
  { id: '12-schema-markup', agentId: '12', label: 'Schema markup rich snippets', category: 'SEO tecnico', description: 'Structured data', prompt: 'Schema markup completo {{cliente}}: Organization, Product (com price/rating), FAQ, Review, Article, HowTo, Event (se aplicavel). JSON-LD pronto para paste em <head>. Validar com Rich Results Test.' },
  { id: '12-a-b-test-vwo', agentId: '12', label: 'Setup A/B test (VWO/Optimize)', category: 'CRO', description: 'Teste tecnico', prompt: 'Setup A/B test tecnico {{cliente}} VWO/Optimize: instalacao script, definicao objetivo, goals+custom metrics, variacao via visual editor ou codigo, sample size calc, publicacao, interpretacao estatistica.' },
  { id: '12-api-integration', agentId: '12', label: 'API integration plan', category: 'Backend', description: 'Integrar sistemas', prompt: 'Plano integracao API {{cliente}} conectando [sistema A] <-> [B]: auth (OAuth2/API key), endpoints necessarios, rate limits, error handling, webhooks, logs, security, doc OpenAPI.' },
  { id: '12-headless-cms', agentId: '12', label: 'Migracao Headless CMS', category: 'Arquitetura', description: 'De WP para headless', prompt: 'Plano migracao {{cliente}} WordPress tradicional para headless (Next.js + Strapi/Contentful): arquitetura, migracao conteudo, SEO preservation, performance goals, cronograma 6 semanas, riscos+mitigacao.' },

  // ===== AGENTE 13 - DADOS & BI =====
  { id: '13-dashboard-kpis', agentId: '13', label: 'Dashboard KPIs Looker', category: 'Dashboard', description: 'AEMR 4 pilares', prompt: 'Dashboard Looker Studio {{cliente}} AEMR: (1)Aquisicao (sessoes/trafego canal/CPL/ROAS), (2)Engajamento (ER/tempo/pag.sessao), (3)Monetizacao (receita/conv/ticket), (4)Retencao (churn/NPS/LTV). MoM+YoY. Data sources (GA4, Meta, Google Ads, CRM).' },
  { id: '13-attribution-model', agentId: '13', label: 'Modelo atribuicao multi-touch', category: 'Atribuicao', description: 'Compare 6 modelos', prompt: 'Modelo atribuicao multi-touch {{cliente}}: compare (1)last click, (2)first click, (3)linear, (4)time decay, (5)position based, (6)data-driven. Recomende ideal. Analise ROI/canal com cada modelo.' },
  { id: '13-cohort-analysis', agentId: '13', label: 'Cohort analysis retencao', category: 'Cohort', description: 'Por mes aquisicao', prompt: 'Cohort analysis {{cliente}}: agrupe clientes por mes aquisicao, retencao M1/M3/M6/M12. Identifique: melhor cohort e porque, pior e causas, padroes sazonais, impacto mudancas produto, recomendacoes retencao proximas.' },
  { id: '13-ltv-calc', agentId: '13', label: 'Calculo LTV por segmento', category: 'LTV', description: 'Por segmento/canal', prompt: 'Calculo LTV {{cliente}} por segmento+canal aquisicao: formula (ticket_medio × freq_compra × margem × vida_util_anos). Top 3 segmentos high-LTV, bottom 3 low-LTV. Decisoes orcamentarias (payback < 3 meses).' },
  { id: '13-ab-test-stats', agentId: '13', label: 'Analise estatistica A/B test', category: 'Estatistica', description: 'Significancia + confianca', prompt: 'Analise estatistica A/B {{cliente}}: teste Z/Chi-square, p-value, significancia 95%, uplift, intervalos confianca, sample size pos-hoc. Decisao conservadora (go/no-go/mais tempo).' },
  { id: '13-segmentacao-rfm', agentId: '13', label: 'Segmentacao RFM clientes', category: 'Segmentacao', description: 'Recency/Frequency/Monetary', prompt: 'Segmentacao RFM base clientes {{cliente}}: score 1-5 em Recency+Frequency+Monetary. Segmentos (Champions 555/Loyal/Potential/At Risk/Lost). Acoes por segmento (win-back, upsell, nurture).' },
  { id: '13-predictive-churn', agentId: '13', label: 'Modelo preditivo churn', category: 'ML', description: 'Identificar risco churn', prompt: 'Modelo preditivo churn {{cliente}}: features (comportamento, tenure, NPS, suporte), scoring 0-100, thresholds (alerta >60, critico >85), acoes automatizadas (email retencao, oferta especial, contato proativo).' },

  // ===== AGENTE 14 - SEO =====
  { id: '14-audit-completo', agentId: '14', label: 'Audit SEO completo', category: 'Audit', description: 'Tecnico + conteudo + backlinks', prompt: 'Audit SEO completo {{cliente}}: (1)Tecnico (velocidade, mobile, indexacao, sitemap, schema, canonical), (2)On-page (titles, desc, H1, kwd density, links internos, imgs), (3)Conteudo (gaps vs competitors, E-E-A-T, topic authority), (4)Backlinks (perfil, anchors, toxic), (5)Local SEO. Top 20 acoes priorizadas impacto/esforco.' },
  { id: '14-keyword-research', agentId: '14', label: 'Keyword research 50+', category: 'Keywords', description: 'Por intent + dificuldade', prompt: 'Keyword research {{cliente}} ({{segmento}}) 50+ keywords: (1)branded, (2)produto/servico, (3)problema/dor, (4)comparacao, (5)informacional long-tail. Volume mensal, dificuldade, CPC, intent, SERP features, URL sugerida. Cluster em topic hubs.' },
  { id: '14-link-building', agentId: '14', label: 'Plano link building', category: 'Links', description: '6 taticas white-hat', prompt: 'Plano link building white-hat {{cliente}}: (1)HARO/Qwoted, (2)broken link building, (3)skyscraper, (4)guest posts top 10 blogs segmento, (5)digital PR (pesquisas/infograficos), (6)parcerias, (7)directories relevantes. Meta 20 backlinks DR>30 em 90d.' },
  { id: '14-content-cluster', agentId: '14', label: 'Topic cluster (1 pillar + 10 spokes)', category: 'Cluster', description: 'Pillar+spokes', prompt: 'Topic cluster {{cliente}} tema X: 1 pillar page (guia definitivo 4000+ pal) + 10 spoke posts (800-1500 pal cada) + internal links. Keywords, angulos, estrutura, cronograma.' },
  { id: '14-local-seo', agentId: '14', label: 'Local SEO + Google Business Profile', category: 'Local', description: 'Otimizacao GBP', prompt: 'Local SEO {{cliente}}: Google Business Profile completo (categorias, horarios, fotos, servicos), citations NAP, reviews strategy, local keywords, Maps pack ranking, local link building.' },
  { id: '14-featured-snippets', agentId: '14', label: 'Otimizacao featured snippets', category: 'SERP', description: 'Posicao 0', prompt: 'Plano otimizacao featured snippets {{cliente}}: identificar 20 keywords com snippet oportunidade, formato (paragraph/list/table/video), template H2 pergunta + resposta direta 40-50 palavras, update on-page.' },
  { id: '14-international-seo', agentId: '14', label: 'International SEO (hreflang)', category: 'I18n', description: 'Multi-idioma/pais', prompt: 'Plano International SEO {{cliente}}: hreflang setup, estrutura URL (subdomain/subfolder/ccTLD), keyword research por pais, cultural adaptation conteudo, link building local, GSC setup por pais.' },

  // ===== AGENTE 15 - VIDEO =====
  { id: '15-youtube-10min', agentId: '15', label: 'Roteiro YouTube 10min', category: 'YouTube', description: 'Roteiro completo', prompt: 'Roteiro COMPLETO YouTube 10min {{cliente}} sobre [TEMA]: (0-15s) Hook irresistivel, (15-30s) Pattern interrupt + promessa, (30s-1min) Credibilidade, (1-8min) 3-5 pontos com provas/exemplos, (8-9min) CTA principal+secundario, (9-10min) Outro -> proximo video. Marcacoes B-roll, cortes, CTAs visuais.' },
  { id: '15-reels-5-scripts', agentId: '15', label: '5 scripts Reels virais', category: 'Reels', description: 'Scripts 30-60s', prompt: '5 scripts Reels 30-60s {{cliente}}: (1)3 erros que voce comete, (2)tutorial rapido, (3)antes/depois, (4)mito vs verdade, (5)bastidores/POV. Hook 3s, desenvolvimento punchline, CTA verbal+visual, audio trending, legendas.' },
  { id: '15-shorts-estrategia', agentId: '15', label: 'Estrategia YouTube Shorts', category: 'Shorts', description: 'Plano 30 videos', prompt: 'Estrategia YouTube Shorts {{cliente}}: 30 ideas videos 60s, hooks nos 3s, 5 categorias (dicas rapidas, listas, antes/depois, stories, perguntas). Cadencia diaria, CTAs para canal principal, metricas CTR/retention.' },
  { id: '15-video-sales-letter', agentId: '15', label: 'Video Sales Letter 10min', category: 'VSL', description: 'Video vendas longo', prompt: 'VSL 10min {{cliente}}: estrutura polida (hook+agitacao+solucao+prova+oferta+urgencia+CTA), imagem/slides/B-roll por bloco, tempo por secao, voz/tom recomendado. Roteiro palavra-por-palavra.' },
  { id: '15-live-event-production', agentId: '15', label: 'Roteiro evento ao vivo', category: 'Live', description: 'Produzir live/webinar', prompt: 'Roteiro live/webinar 60min {{cliente}}: abertura 5min+hook, 3 blocos conteudo 15min cada com slides, Q&A 10min, pitch 10min, CTAs intermediarios. Checklist tecnico (OBS, multi-cam, chat, gravacao).' },
  { id: '15-ugc-brief', agentId: '15', label: 'Brief UGC creator', category: 'UGC', description: 'Brief para creator produzir', prompt: 'Brief UGC {{cliente}} para creator produzir: produto info, pontos-chave, 3 angulos sugeridos, do/dont, specs tecnicas (iluminacao, audio, vertical 9:16), duration, tone. Template de briefing email.' },
  { id: '15-tiktok-trend-jack', agentId: '15', label: 'Trend jacking TikTok', category: 'Trending', description: 'Aproveitar trends', prompt: 'Lista 10 trends TikTok ultima semana com potencial para {{cliente}} ({{segmento}}): audio trending, estrutura, como adaptar ao nicho, exemplos de brands que fizeram, risco vs potencial viral.' },

  // ===== AGENTE 16 - CRO/UX =====
  { id: '16-audit-lift', agentId: '16', label: 'Audit CRO (LIFT Model)', category: 'Audit', description: '6 dimensoes LIFT', prompt: 'Audit CRO {{cliente}} LIFT Model 6 dimensoes: (1)Proposta Valor clareza, (2)Relevancia match trafego, (3)Clareza hierarquia, (4)Ansiedade atritos, (5)Distracao elementos, (6)Urgencia escassez. Score 1-10 cada. Top 10 hipoteses teste ICE.' },
  { id: '16-ab-test-5', agentId: '16', label: '5 testes A/B priorizados', category: 'A/B', description: 'Hipoteses ICE', prompt: '5 testes A/B {{cliente}} priorizados ICE. Cada: hipotese "Se X entao Y porque Z", control, treatment, metrica primaria, secundarias, sample size min, duracao, ICE (Impact x Confidence x Ease). Quick wins primeiro.' },
  { id: '16-heatmap-analysis', agentId: '16', label: 'Analise heatmaps/recordings', category: 'Heatmap', description: 'Insights acionaveis', prompt: 'Analise heatmaps+recordings {{cliente}}: (1)dead clicks, (2)rage clicks, (3)scroll depth medio, (4)pontos abandono, (5)elementos ignorados, (6)patterns navegacao inesperados. Top 10 acoes corretivas.' },
  { id: '16-checkout-opt', agentId: '16', label: 'Otimizar checkout e-com', category: 'Checkout', description: 'Reduzir abandono', prompt: 'Otimizar checkout {{cliente}} e-commerce: analise step-by-step (cart>info>shipping>payment>confirm), identificar gargalos cada etapa, 10 melhorias priorizadas (guest checkout, auto-fill, trust badges, progress bar, exit intent).' },
  { id: '16-user-journey', agentId: '16', label: 'User Journey Map', category: 'UX Research', description: 'Jornada + pain points', prompt: 'User Journey Map {{cliente}}: 5 stages (awareness/consideration/decision/purchase/retention), touchpoints cada, thoughts/feelings/pain points, oportunidades otimizacao. Visual em markdown.' },
  { id: '16-form-optimization', agentId: '16', label: 'Otimizacao formularios', category: 'Forms', description: 'Reduzir friction', prompt: 'Otimizacao formularios {{cliente}}: analise form atual, reducao campos (so essenciais), inline validation, conditional logic, progressive profiling, mobile-first UX, A/B test copy submit button.' },
  { id: '16-mobile-ux-audit', agentId: '16', label: 'Mobile UX audit', category: 'Mobile', description: 'Mobile-first review', prompt: 'Audit UX mobile {{cliente}}: checklist 30 itens (touch targets 44px, fontes legiveis 16px+, spacing, menu hamburger, CTAs sticky, forms friendly, performance, thumb zone). Score + plano.' },
];

export function getCommandsForAgent(agentId: string): QuickCommand[] {
  return QUICK_COMMANDS.filter((c) => c.agentId === agentId);
}

export function applyCommandPlaceholders(command: QuickCommand, ctx: {
  cliente?: string;
  segmento?: string;
  step?: string;
  pilar?: string;
}): string {
  return applyPlaceholders(command.prompt, ctx);
}

export function getTotalCommandsCount(): number {
  return QUICK_COMMANDS.length;
}
