import type { Agent } from './types';

export const AGENTS: Agent[] = [
  {
    id: '01',
    name: 'Mestre Estrategista',
    area: 'Orquestracao',
    icon: '\u2655',
    color: '#ff4444',
    pilar: 'Todos',
    mentors: 'Kotler, Sean Ellis, Goldratt',
    frameworks: 'STP, AARRR, TOC, ICE',
    kpis: 'Sprint Velocity, STEP Progress',
    tools: 'Google Analytics, SEMrush',
    quickActions: ['Diagnostico STEP', 'Sprint Planning', 'Relatorio Mensal', 'Analise Gargalos TOC', 'Priorizacao AARRR'],
  },
  {
    id: '02',
    name: 'Gestor de Projetos',
    area: 'Sprints/OKR',
    icon: '\uD83D\uDCCB',
    color: '#448aff',
    pilar: 'Todos',
    mentors: 'Schwaber, Sutherland, Doerr',
    frameworks: 'Scrum, Kanban, OKR, RACI',
    kpis: 'Sprint Completion, Cycle Time',
    tools: 'Jira, Notion, Trello',
    quickActions: ['Sprint Board', 'OKRs Trimestre', 'Backlog Priorizado', 'RACI Matrix', 'Retrospectiva'],
  },
  {
    id: '03',
    name: 'Trafego Google',
    area: 'Google Ads',
    icon: '\uD83D\uDD0D',
    color: '#4285f4',
    pilar: 'Aquisicao',
    mentors: 'Brad Geddes, Frederick Vallaeys',
    frameworks: 'SKAGs, Quality Score, PMax',
    kpis: 'CPC, CTR, ROAS, Quality Score',
    tools: 'Google Ads, Keyword Planner',
    quickActions: ['Estrutura Campanha', 'Audit Quality Score', 'Performance Max', 'Keywords Negativas', 'Orcamento Otimo'],
  },
  {
    id: '04',
    name: 'Trafego Meta',
    area: 'Meta Ads',
    icon: '\uD83D\uDE80',
    color: '#1877f2',
    pilar: 'Aquisicao',
    mentors: 'Andrew Foxwell, Jon Loomer',
    frameworks: 'CBO, ABO, CAPI, Lookalike',
    kpis: 'CPL, CPM, ROAS, Frequencia',
    tools: 'Meta Business Suite, Ads Manager',
    quickActions: ['Campanha Conversao', 'Escala Orcamento', 'Lookalike Audiences', 'Retargeting Funil', 'Creative Testing'],
  },
  {
    id: '05',
    name: 'Designer Ads',
    area: 'Criativos Ads',
    icon: '\uD83C\uDFA8',
    color: '#ff6b6b',
    pilar: 'Aquisicao',
    mentors: 'Sagmeister, Ogilvy',
    frameworks: 'AIDA Visual, Specs por canal',
    kpis: 'CTR Criativo, Hook Rate',
    tools: 'Figma, Canva, Photoshop',
    quickActions: ['Brief Criativo', 'Pack Anuncios', 'Variacao A/B', 'Specs por Canal', 'Refresh Criativos'],
  },
  {
    id: '06',
    name: 'Designer Social',
    area: 'Design Social',
    icon: '\uD83C\uDF08',
    color: '#e040fb',
    pilar: 'Engajamento',
    mentors: 'Chris Do, Jessica Walsh',
    frameworks: 'Grid System, Brand Guide',
    kpis: 'Engagement Visual, Brand Consistency',
    tools: 'Figma, Canva, Illustrator',
    quickActions: ['Brand Guidelines', 'Templates Social', 'Carousel Design', 'Stories Pack', 'Visual Identity'],
  },
  {
    id: '07',
    name: 'Social Media',
    area: 'Calendario/Engajamento',
    icon: '\uD83D\uDCF1',
    color: '#00bcd4',
    pilar: 'Engajamento',
    mentors: 'Gary Vee, Ann Handley',
    frameworks: '70/20/10, Jab Jab Right Hook',
    kpis: 'Engagement Rate, Alcance, Crescimento',
    tools: 'mLabs, Hootsuite',
    quickActions: ['Calendario Editorial', 'Pack Legendas', 'Estrategia Hashtags', 'Analise Concorrentes', 'Plano Conteudo'],
  },
  {
    id: '08',
    name: 'Copy Performance',
    area: 'Headlines/CTAs/LP',
    icon: '\u270D\uFE0F',
    color: '#ff9100',
    pilar: 'Monetizacao',
    mentors: 'Eugene Schwartz, Gary Halbert',
    frameworks: 'PAS, AIDA, Headlines',
    kpis: 'CTR Copy, Conv Rate LP',
    tools: 'Unbounce, Google Optimize',
    quickActions: ['Copy Landing Page', 'Headlines A/B', 'CTAs Otimizados', 'Email Vendas', 'Scripts Anuncios'],
  },
  {
    id: '09',
    name: 'Copy Conteudo',
    area: 'Blog/Email/Ebooks',
    icon: '\uD83D\uDCD6',
    color: '#66bb6a',
    pilar: 'Engajamento',
    mentors: 'Ann Handley, Joe Pulizzi',
    frameworks: 'Content Pillars, SEO Writing',
    kpis: 'Trafego Organico, Email Open Rate',
    tools: 'WordPress, Mailchimp, RD',
    quickActions: ['Artigo Blog', 'Sequencia Email', 'E-book', 'Newsletter', 'Case Study'],
  },
  {
    id: '10',
    name: 'Automacoes',
    area: 'Fluxos/MarTech',
    icon: '\u2699\uFE0F',
    color: '#78909c',
    pilar: 'Retencao',
    mentors: 'Scott Brinker',
    frameworks: 'Lead Scoring, Webhooks, Zapier',
    kpis: 'Lead Score Accuracy, Automation Rate',
    tools: 'RD Station, ActiveCampaign, Zapier',
    quickActions: ['Fluxo Nutricao', 'Lead Scoring', 'Webhook Setup', 'Integracao CRM', 'Automacao Email'],
  },
  {
    id: '11',
    name: 'CRM & Pipeline',
    area: 'Vendas/RevOps',
    icon: '\uD83D\uDCB0',
    color: '#ffd600',
    pilar: 'Monetizacao',
    mentors: 'Aaron Ross, Mark Roberge',
    frameworks: 'Predictable Revenue, BANT',
    kpis: 'SQL Rate, Win Rate, Ticket Medio',
    tools: 'Pipedrive, HubSpot, RD CRM',
    quickActions: ['Pipeline Review', 'Scripts Vendas', 'Cadencia Followup', 'Forecast Receita', 'Qualificacao BANT'],
  },
  {
    id: '12',
    name: 'Web Dev',
    area: 'LP/GTM/GA4/Tracking',
    icon: '\uD83D\uDCBB',
    color: '#26c6da',
    pilar: 'Aquisicao',
    mentors: 'Steve Krug, Vitaly Friedman',
    frameworks: 'Core Web Vitals, Schema',
    kpis: 'Page Speed, Conv Rate, Tracking Accuracy',
    tools: 'GTM, GA4, WordPress, Webflow',
    quickActions: ['Setup GA4/GTM', 'Landing Page', 'Core Web Vitals', 'Schema Markup', 'Tracking Events'],
  },
  {
    id: '13',
    name: 'Dados & BI',
    area: 'Dashboards/Atribuicao',
    icon: '\uD83D\uDCC8',
    color: '#ab47bc',
    pilar: 'Todos',
    mentors: 'Avinash Kaushik, Brent Dykes',
    frameworks: 'Data Storytelling, Cohort',
    kpis: 'Data Accuracy, Report Frequency',
    tools: 'Looker Studio, BigQuery, GA4',
    quickActions: ['Dashboard KPIs', 'Modelo Atribuicao', 'Cohort Analysis', 'Report Automatico', 'Data Storytelling'],
  },
  {
    id: '14',
    name: 'SEO',
    area: 'Keywords/Tecnico/Links',
    icon: '\uD83D\uDD0D',
    color: '#8bc34a',
    pilar: 'Aquisicao',
    mentors: 'Rand Fishkin, Brian Dean',
    frameworks: 'E-E-A-T, Skyscraper, Clusters',
    kpis: 'Posicoes Top 10, Trafego Organico',
    tools: 'Ahrefs, SEMrush, Search Console',
    quickActions: ['Audit SEO Completo', 'Keyword Research', 'Cluster Tematico', 'Link Building', 'SEO Tecnico'],
  },
  {
    id: '15',
    name: 'Video',
    area: 'Roteiros/YouTube/Reels',
    icon: '\uD83C\uDFAC',
    color: '#f44336',
    pilar: 'Engajamento',
    mentors: 'MrBeast, Casey Neistat',
    frameworks: 'Hook 3s, Storytelling',
    kpis: 'View Rate, Retention, Hook Rate',
    tools: 'Premiere, CapCut, YouTube Studio',
    quickActions: ['Roteiro YouTube', 'Script Reels', 'Calendario Videos', 'Thumbnail Brief', 'Estrategia Canal'],
  },
  {
    id: '16',
    name: 'CRO/UX',
    area: 'Testes A/B/Heatmaps',
    icon: '\uD83D\uDD2C',
    color: '#ff7043',
    pilar: 'Monetizacao',
    mentors: 'Peep Laja, Steve Krug',
    frameworks: 'LIFT Model, Fogg Behavior',
    kpis: 'Conv Rate, Test Win Rate',
    tools: 'Hotjar, VWO, Clarity',
    quickActions: ['Audit CRO', 'Teste A/B', 'Heatmap Analysis', 'User Journey', 'Checkout Optimization'],
  },
];

export const DEFAULT_CLIENTS = [
  { name: 'ASHEY FIBRA', segment: 'Fibra Optica/Telecom', step: 'Executar' as const, pilar: 'Aquisicao' as const, health: 'green' as const },
  { name: 'BOX ACNT', segment: 'Containers', step: 'Ter' as const, pilar: 'Aquisicao' as const, health: 'yellow' as const },
  { name: 'DPRINT', segment: 'Impressao', step: 'Executar' as const, pilar: 'Monetizacao' as const, health: 'green' as const },
  { name: 'INOVUS ECNC', segment: 'Economia/Consultoria', step: 'Saber' as const, pilar: 'Engajamento' as const, health: 'yellow' as const },
  { name: 'MAIS CONFECCOES', segment: 'Confeccao/Uniformes B2B', step: 'Ter' as const, pilar: 'Aquisicao' as const, health: 'green' as const },
  { name: 'NOSSO RUMO', segment: 'Educacao', step: 'Saber' as const, pilar: 'Engajamento' as const, health: 'red' as const },
  { name: 'RANDA PORTAS', segment: 'Portas/Construcao', step: 'Executar' as const, pilar: 'Monetizacao' as const, health: 'green' as const },
  { name: 'RING TECNOLOGIA', segment: 'Tecnologia/RFID Hospitalar', step: 'Ter' as const, pilar: 'Aquisicao' as const, health: 'yellow' as const },
  { name: 'SEMPER LASER', segment: 'Laser/Industrial', step: 'Potencializar' as const, pilar: 'Retencao' as const, health: 'green' as const },
  { name: 'WE BELLA', segment: 'Beleza/Estetica', step: 'Executar' as const, pilar: 'Monetizacao' as const, health: 'yellow' as const },
];

export function getAgentById(id: string): Agent | undefined {
  return AGENTS.find((a) => a.id === id);
}

export function getAgentsByPilar(pilar: string): Agent[] {
  if (pilar === 'Todos') return AGENTS;
  return AGENTS.filter((a) => a.pilar === pilar || a.pilar === 'Todos');
}
