const ROUTING_TABLE: Record<string, string[]> = {
  'estrategia': ['01'],
  'diagnostico': ['01'],
  'priorizacao': ['01'],
  'gargalo': ['01'],
  'toc': ['01'],
  'sprint': ['02'],
  'okr': ['02'],
  'backlog': ['02'],
  'raci': ['02'],
  'projeto': ['02'],
  'google ads': ['03'],
  'search ads': ['03'],
  'pmax': ['03'],
  'performance max': ['03'],
  'shopping': ['03'],
  'quality score': ['03'],
  'meta ads': ['04'],
  'facebook ads': ['04'],
  'instagram ads': ['04'],
  'lookalike': ['04'],
  'cbo': ['04'],
  'criativo': ['05'],
  'banner': ['05'],
  'anuncio visual': ['05'],
  'design social': ['06'],
  'brand': ['06'],
  'identidade visual': ['06'],
  'calendario editorial': ['07'],
  'legenda': ['07'],
  'hashtag': ['07'],
  'social media': ['07'],
  'copy lp': ['08'],
  'headline': ['08'],
  'cta': ['08'],
  'landing page copy': ['08'],
  'copy performance': ['08'],
  'blog': ['09'],
  'email': ['09'],
  'ebook': ['09'],
  'newsletter': ['09'],
  'conteudo': ['09'],
  'automacao': ['10'],
  'fluxo': ['10'],
  'lead scoring': ['10'],
  'webhook': ['10'],
  'zapier': ['10'],
  'crm': ['11'],
  'pipeline': ['11'],
  'venda': ['11'],
  'forecast': ['11'],
  'landing page': ['12'],
  'gtm': ['12'],
  'ga4': ['12'],
  'tracking': ['12'],
  'web': ['12'],
  'dashboard': ['13'],
  'bi': ['13'],
  'atribuicao': ['13'],
  'dados': ['13'],
  'seo': ['14'],
  'keyword': ['14'],
  'link building': ['14'],
  'video': ['15'],
  'roteiro': ['15'],
  'youtube': ['15'],
  'reels': ['15'],
  'cro': ['16'],
  'teste a/b': ['16'],
  'heatmap': ['16'],
  'ux': ['16'],
};

export function routeQuery(query: string): string[] {
  const q = query.toLowerCase();
  for (const [keyword, agents] of Object.entries(ROUTING_TABLE)) {
    if (q.includes(keyword)) return agents;
  }
  return ['01'];
}

export function getRoutingTable(): typeof ROUTING_TABLE {
  return ROUTING_TABLE;
}
