-- Seed dos 16 agentes do V4 PIT WALL
-- Execute apos 001_initial_schema.sql

INSERT INTO public.agents (id, name, area, icon, color, pilar, mentors, frameworks, kpis, tools, quick_actions) VALUES
('01', 'Mestre Estrategista', 'Orquestracao', E'\u2655', '#ff4444', 'Todos', 'Kotler, Sean Ellis, Goldratt', 'STP, AARRR, TOC, ICE', 'Sprint Velocity, STEP Progress', 'Google Analytics, SEMrush', ARRAY['Diagnostico STEP', 'Sprint Planning', 'Relatorio Mensal', 'Analise Gargalos TOC', 'Priorizacao AARRR']),
('02', 'Gestor de Projetos', 'Sprints/OKR', E'\U0001F4CB', '#448aff', 'Todos', 'Schwaber, Sutherland, Doerr', 'Scrum, Kanban, OKR, RACI', 'Sprint Completion, Cycle Time', 'Jira, Notion, Trello', ARRAY['Sprint Board', 'OKRs Trimestre', 'Backlog Priorizado', 'RACI Matrix', 'Retrospectiva']),
('03', 'Trafego Google', 'Google Ads', E'\U0001F50D', '#4285f4', 'Aquisicao', 'Brad Geddes, Frederick Vallaeys', 'SKAGs, Quality Score, PMax', 'CPC, CTR, ROAS, Quality Score', 'Google Ads, Keyword Planner', ARRAY['Estrutura Campanha', 'Audit Quality Score', 'Performance Max', 'Keywords Negativas', 'Orcamento Otimo']),
('04', 'Trafego Meta', 'Meta Ads', E'\U0001F680', '#1877f2', 'Aquisicao', 'Andrew Foxwell, Jon Loomer', 'CBO, ABO, CAPI, Lookalike', 'CPL, CPM, ROAS, Frequencia', 'Meta Business Suite, Ads Manager', ARRAY['Campanha Conversao', 'Escala Orcamento', 'Lookalike Audiences', 'Retargeting Funil', 'Creative Testing']),
('05', 'Designer Ads', 'Criativos Ads', E'\U0001F3A8', '#ff6b6b', 'Aquisicao', 'Sagmeister, Ogilvy', 'AIDA Visual, Specs por canal', 'CTR Criativo, Hook Rate', 'Figma, Canva, Photoshop', ARRAY['Brief Criativo', 'Pack Anuncios', 'Variacao A/B', 'Specs por Canal', 'Refresh Criativos']),
('06', 'Designer Social', 'Design Social', E'\U0001F308', '#e040fb', 'Engajamento', 'Chris Do, Jessica Walsh', 'Grid System, Brand Guide', 'Engagement Visual, Brand Consistency', 'Figma, Canva, Illustrator', ARRAY['Brand Guidelines', 'Templates Social', 'Carousel Design', 'Stories Pack', 'Visual Identity']),
('07', 'Social Media', 'Calendario/Engajamento', E'\U0001F4F1', '#00bcd4', 'Engajamento', 'Gary Vee, Ann Handley', '70/20/10, Jab Jab Right Hook', 'Engagement Rate, Alcance, Crescimento', 'mLabs, Hootsuite', ARRAY['Calendario Editorial', 'Pack Legendas', 'Estrategia Hashtags', 'Analise Concorrentes', 'Plano Conteudo']),
('08', 'Copy Performance', 'Headlines/CTAs/LP', E'\u270D\uFE0F', '#ff9100', 'Monetizacao', 'Eugene Schwartz, Gary Halbert', 'PAS, AIDA, Headlines', 'CTR Copy, Conv Rate LP', 'Unbounce, Google Optimize', ARRAY['Copy Landing Page', 'Headlines A/B', 'CTAs Otimizados', 'Email Vendas', 'Scripts Anuncios']),
('09', 'Copy Conteudo', 'Blog/Email/Ebooks', E'\U0001F4D6', '#66bb6a', 'Engajamento', 'Ann Handley, Joe Pulizzi', 'Content Pillars, SEO Writing', 'Trafego Organico, Email Open Rate', 'WordPress, Mailchimp, RD', ARRAY['Artigo Blog', 'Sequencia Email', 'E-book', 'Newsletter', 'Case Study']),
('10', 'Automacoes', 'Fluxos/MarTech', E'\u2699\uFE0F', '#78909c', 'Retencao', 'Scott Brinker', 'Lead Scoring, Webhooks, Zapier', 'Lead Score Accuracy, Automation Rate', 'RD Station, ActiveCampaign, Zapier', ARRAY['Fluxo Nutricao', 'Lead Scoring', 'Webhook Setup', 'Integracao CRM', 'Automacao Email']),
('11', 'CRM & Pipeline', 'Vendas/RevOps', E'\U0001F4B0', '#ffd600', 'Monetizacao', 'Aaron Ross, Mark Roberge', 'Predictable Revenue, BANT', 'SQL Rate, Win Rate, Ticket Medio', 'Pipedrive, HubSpot, RD CRM', ARRAY['Pipeline Review', 'Scripts Vendas', 'Cadencia Followup', 'Forecast Receita', 'Qualificacao BANT']),
('12', 'Web Dev', 'LP/GTM/GA4/Tracking', E'\U0001F4BB', '#26c6da', 'Aquisicao', 'Steve Krug, Vitaly Friedman', 'Core Web Vitals, Schema', 'Page Speed, Conv Rate, Tracking Accuracy', 'GTM, GA4, WordPress, Webflow', ARRAY['Setup GA4/GTM', 'Landing Page', 'Core Web Vitals', 'Schema Markup', 'Tracking Events']),
('13', 'Dados & BI', 'Dashboards/Atribuicao', E'\U0001F4C8', '#ab47bc', 'Todos', 'Avinash Kaushik, Brent Dykes', 'Data Storytelling, Cohort', 'Data Accuracy, Report Frequency', 'Looker Studio, BigQuery, GA4', ARRAY['Dashboard KPIs', 'Modelo Atribuicao', 'Cohort Analysis', 'Report Automatico', 'Data Storytelling']),
('14', 'SEO', 'Keywords/Tecnico/Links', E'\U0001F50D', '#8bc34a', 'Aquisicao', 'Rand Fishkin, Brian Dean', 'E-E-A-T, Skyscraper, Clusters', 'Posicoes Top 10, Trafego Organico', 'Ahrefs, SEMrush, Search Console', ARRAY['Audit SEO Completo', 'Keyword Research', 'Cluster Tematico', 'Link Building', 'SEO Tecnico']),
('15', 'Video', 'Roteiros/YouTube/Reels', E'\U0001F3AC', '#f44336', 'Engajamento', 'MrBeast, Casey Neistat', 'Hook 3s, Storytelling', 'View Rate, Retention, Hook Rate', 'Premiere, CapCut, YouTube Studio', ARRAY['Roteiro YouTube', 'Script Reels', 'Calendario Videos', 'Thumbnail Brief', 'Estrategia Canal']),
('16', 'CRO/UX', 'Testes A/B/Heatmaps', E'\U0001F52C', '#ff7043', 'Monetizacao', 'Peep Laja, Steve Krug', 'LIFT Model, Fogg Behavior', 'Conv Rate, Test Win Rate', 'Hotjar, VWO, Clarity', ARRAY['Audit CRO', 'Teste A/B', 'Heatmap Analysis', 'User Journey', 'Checkout Optimization'])
ON CONFLICT (id) DO NOTHING;
